language: c

branches:
    only:
        - master
build:
    ci:
      - cd shippable
      - docker build -t zephyrprojectrtos/ci:$BRANCH.$BUILD_NUMBER .
    post_ci:
      - docker push zephyrprojectrtos/ci:$BRANCH.$BUILD_NUMBER

integrations:
  hub:
    - integrationName: DH-Integration
      type: docker
